apiVersion: v1
kind: Secret
metadata:
  name: ecr-aws-credentials
data:
  AWS_ACCESS_KEY_ID: '' #base-64 encoded aws access key with ecr access, run echo -n "PUT_ACCESSKEY_HERE" | base64
  AWS_SECRET_ACCESS_KEY: '' #base-64 encoded aws access key with ecr access, echo -n "PUT_SECRETKEY_HERE" | base64