apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
    - name: private-reg-container
      image: 668531211233.dkr.ecr.ap-southeast-1.amazonaws.com/voltrans/gnt:latest
  imagePullSecrets:
    - name: ecr